#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     irSensor,       sensorHiTechnicIRSeeker600)
#pragma config(Motor,  mtr_S1_C1_1,     leftWheel,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     firstPickupMotor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightWheel,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     liftMotor,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1, 	secondPickupMotor,	tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     liftMotor,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    irServo,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    clampServo,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    dropServo,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//#pragma config(Motor,  mtr_S1_C4_1,     liftMotor,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "includes.h"
#include "teleopFunctions.h"

// main function
task main() {
	initializeGlobalVariables();

	while (true) {
		Joystick_UpdateData();

			// driving segment

		// controls the left wheel
		motor[leftWheel] = Joystick_GenericInput(JOYSTICK_L, AXIS_Y, CONTROLLER_1);
		// controls the right wheel
		motor[rightWheel] = Joystick_GenericInput(JOYSTICK_R, AXIS_Y, CONTROLLER_1);

		// loop controlling the lift
		if(!isLift) {
			// for the lowest rolling goal
			if(Joystick_ButtonPressed(BUTTON_A, CONTROLLER_2) && position == down) {
				Task_Spawn(t_raiseLiftLow);
				position = upLow;
			}
			// for the middle rolling goal
			else if(Joystick_ButtonPressed(BUTTON_B, CONTROLLER_2) && position == down) {
				Task_Spawn(t_raiseLiftMiddle);
				position = upMiddle;
			}

			// for the highest rolling goal (Currently not in use)
			//else if(Joystick_ButtonPressed(BUTTON_Y, CONTROLLER_2) && position == down) {
			//	Task_Spawn(t_raiseLiftHigh);
			//	position = upHigh;
			//}
			//// for the center goal (Currently not in use)
			//else if(Joystick_ButtonPressed(BUTTON_X, CONTROLLER_2) && position == down) {
			//	Task_Spawn(t_raiseLiftCenter);
 		//		position = upCenter;
			//}

			// lowers the lift all the way to the ground
 			else if(Joystick_ButtonPressed(BUTTON_START, CONTROLLER_2) && position != down) {
				Task_Spawn(t_lowerLift);
				position = down;
			}

				// for minor lift changes
			// raises lift slightly
			if(Joystick_Button(BUTTON_RB, CONTROLLER_2)) {
				isLift = true;
				Task_Spawn(t_raiseLiftSlightly);
			}
			else if(Joystick_ButtonReleased(BUTTON_RB, CONTROLLER_2)) {
				isLift = false;
				Task_Kill(t_raiseLiftSlightly);
			}

			// lowers the lift slightly
			if(Joystick_Button(BUTTON_LB, CONTROLLER_2)) {
				isLift = true;
				Task_Spawn(t_lowerLiftSlightly);
			}
			else if(Joystick_ButtonReleased(BUTTON_LB, CONTROLLER_2)) {
 				isLift = false;
 				Task_Kill(t_lowerLiftSlightly);
 			}
		}

			// loop controlling the pickup
		// for picking up
		if(Joystick_Button(BUTTON_RT, CONTROLLER_1)) {
			Task_Kill(t_reversePickup);
			Task_Spawn(t_startPickup);
		}
		// for releasing
		else if(Joystick_Button(BUTTON_LT, CONTROLLER_1)) {
			Task_Kill(t_startPickup);
			Task_Spawn(t_reversePickup);
		}
		// for stoppping pickup
		else if(Joystick_Button(BUTTON_BACK, CONTROLLER_2) && isPickup == true) {
				Task_Kill(t_startPickup);
				Task_Kill(t_reversePickup);
				Task_Spawn(t_stopPickup);
		}

			// for clamp
		// drops the clamp
		if(Joystick_Button(BUTTON_JOYR, CONTROLLER_2)) {
			Task_Spawn(t_dropClamp);
		}
		if(Joystick_Button(BUTTON_JOYR, CONTROLLER_2)) {
			Task_Spawn(t_raiseClamp);
		}

			// for the drop servo
		// drops the balls
		if(Joystick_Button(BUTTON_RT, CONTROLLER_2)) {
			Task_Spawn(t_dropBall);
		}
		if(Joystick_Button(BUTTON_LT, CONTROLLER_2)) {
			Task_Spawn(t_resetDrop);
		}
		wait1Msec(1);
	}
}
