#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     leftWheel,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     pickupMotor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightWheel,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Blah,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     liftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     liftMotor,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    IRMotor,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "includes.h"
#include "teleopFunctions.h"

// main function
task main() {
	initializeGlobalVariables();

	while (true) {
		Joystick_UpdateData();

			// driving segment

		// controls the left wheel
		motor[leftWheel] = Joystick_GenericInput(JOYSTICK_L, AXIS_Y, CONTROLLER_1);
		// controls the right wheel
		motor[rightWheel] = Joystick_GenericInput(JOYSTICK_R, AXIS_Y, CONTROLLER_1);

		// loop controlling the lift
		// for the lowest rolling goal
		if(Joystick_ButtonReleased(BUTTON_A, CONTROLLER_1) && position == down) {
			Task_Spawn(t_raiseLiftLow);
			position = upLow;
		}
		// for the middle rolling goal
		else if(Joystick_ButtonReleased(BUTTON_B, CONTROLLER_1) && position == down) {
			Task_Spawn(t_raiseLiftMiddle);
			position = upMiddle;
		}
		// for the highest rolling goal
		else if(Joystick_ButtonReleased(BUTTON_Y, CONTROLLER_1) && position == down) {
			Task_Spawn(t_raiseLiftHigh);
			position = upHigh;
		}
		// for the center goal
		else if(Joystick_ButtonReleased(BUTTON_X, CONTROLLER_1) && position == down) {
			Task_Spawn(t_raiseLiftCenter);
 			position = upCenter;
		}
		// lowers the lift all the way to the ground
 		else if(Joystick_ButtonReleased(BUTTON_START, CONTROLLER_1) && position != down) {
			Task_Spawn(t_lowerLift);
			position = down;
		}
		// raises the lift slightly
		if(!isRaising && !isLowering) {
			while(Joystick_Button(BUTTON_RB, CONTROLLER_1))
				isRaising = true;
			isRaising = false;
 		// lowers the lift slightly
			while(Joystick_Button(BUTTON_LB, CONTROLLER_1))
				isLowering = true;
 			isLowering = false;
		}

			// loop controlling the pickup
		// for picking up
		while(Joystick_Button(BUTTON_RT, CONTROLLER_1)) {
			isPicking = true;
			Task_Spawn(t_startPickup);
		}

		// for releasing
		while(Joystick_Button(BUTTON_LT, CONTROLLER_1)) {
			isReversing = true;
			Task_Spawn(t_reversePickup);
		}

		// for stoppping pickup
		if(isPicking == true || isReversing == true) {
			if(Joystick_Button(BUTTON_BACK)) {
				Task_Spawn(t_stopPickup);
			}
		}

		wait1Msec(1);
	}
}
