#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     irSensor,       sensorHiTechnicIRSeeker600)
#pragma config(Motor,  mtr_S1_C1_1,     leftWheel,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     firstPickupMotor,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightWheel,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     liftMotor,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1, 	secondPickupMotor,	tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     liftMotor,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    irServo,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    clampServo,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    dropServo,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "includes.h"
#include "teleopFunctions.h"

// main function
task main() {
	initializeGlobalVariables();

	while (true) {
		Joystick_UpdateData();

			// driving segment

		// the Left Joystick on Controller 1 controls the left wheel
		motor[leftWheel] = Joystick_GenericInput(JOYSTICK_L, AXIS_Y, CONTROLLER_1);
		// the Right Joystick on Controller 1 controls the right wheel
		motor[rightWheel] = Joystick_GenericInput(JOYSTICK_R, AXIS_Y, CONTROLLER_1);

		// loop controlling the lift
		/*if(!isLift) {
			// for the lowest rolling goal
			if(Joystick_ButtonPressed(BUTTON_A, CONTROLLER_2) && position == down) {
				Task_Spawn(t_raiseLiftLow);
				position = upLow;
			}
			// for the middle rolling goal
			else if(Joystick_ButtonPressed(BUTTON_B, CONTROLLER_2) && position == down) {
				Task_Spawn(t_raiseLiftMiddle);
				position = upMiddle;
			}

			// for the highest rolling goal (Currently not in use)
			//else if(Joystick_ButtonPressed(BUTTON_Y, CONTROLLER_2) && position == down) {
			//	Task_Spawn(t_raiseLiftHigh);
			//	position = upHigh;
			//}
			//// for the center goal (Currently not in use)
			//else if(Joystick_ButtonPressed(BUTTON_X, CONTROLLER_2) && position == down) {
			//	Task_Spawn(t_raiseLiftCenter);
 		//		position = upCenter;
			//}

			// lowers the lift all the way to the ground
 			else if(Joystick_ButtonPressed(BUTTON_START, CONTROLLER_2) && position != down) {
				Task_Spawn(t_lowerLift);
				position = down;
			}*/

				// for minor lift changes
			// Holding RB on Controller 2 raises the lift
			if(Joystick_Button(BUTTON_RB, CONTROLLER_2)) {
				isLift = true;
				Task_Spawn(t_raiseLiftSlightly);
			}
			// Releasing RB on Controller 2 stops the lift
			else if(Joystick_ButtonReleased(BUTTON_RB, CONTROLLER_2)) {
				isLift = false;
				Task_Kill(t_raiseLiftSlightly);
				Task_Spawn(t_stopLift);
			}

			// Holding LB on Controller 2 lowers the lift
			if(Joystick_Button(BUTTON_LB, CONTROLLER_2)) {
				isLift = true;
				Task_Spawn(t_lowerLiftSlightly);
			}
			// Releasing LB on Controller 2 stops the lift
			else if(Joystick_ButtonReleased(BUTTON_LB, CONTROLLER_2)) {
 				isLift = false;
 				Task_Kill(t_lowerLiftSlightly);
 				Task_Spawn(t_stopLift);
 			}
			// Pressing Start on Controller 2 stops the lift
 			if(Joystick_Button(BUTTON_START, CONTROLLER_2)) {
 				Task_Kill(t_lowerLiftSlightly);
 				Task_Kill(t_raiseLiftSlightly);
 				Task_Spawn(t_stopLift);
 			}
		//}

			// loop controlling the pickup
		// Holding RT on Controller 1 picks up balls
		if(Joystick_Button(BUTTON_RT, CONTROLLER_1)) {
			Task_Kill(t_reversePickup);
			Task_Spawn(t_startPickup);
		}
		// Releasing RT on Controller 1 stops the pickup
		else if(Joystick_ButtonReleased(BUTTON_RT, CONTROLLER_1)) {
			Task_Kill(t_startPickup);
			Task_Spawn(t_stopPickup);
		}
		// Holding LT on Controller 1 releases balls from the pickup
		else if(Joystick_Button(BUTTON_LT, CONTROLLER_1)) {
			Task_Kill(t_startPickup);
			Task_Spawn(t_reversePickup);
		}
		// Releasing LT on Controller 1 stops the pickup
		else if(Joystick_ButtonReleased(BUTTON_LT, CONTROLLER_1)) {
			Task_Kill(t_reversePickup);
			Task_Spawn(t_stopPickup);
		}

			// for clamp
		// Pressing Button A on Controller 2 drops the clamp
		if(Joystick_Button(BUTTON_A, CONTROLLER_2)) {
			Task_Kill(t_raiseClamp);
			Task_Spawn(t_dropClamp);
		}
		// Pressing Button B on Controller 2 raises the clamp
		if(Joystick_Button(BUTTON_B, CONTROLLER_2)) {
			Task_Kill(t_dropClamp);
			Task_Spawn(t_raiseClamp);
		}

			// for the drop servo
		// Pressing X on Controller 2 drops the balls from the basket
		if(Joystick_Button(BUTTON_X, CONTROLLER_2)) {
			Task_Kill(t_resetDrop);
			Task_Spawn(t_dropBall);
		}
		// Pressing Y on Controller 2 resets the drop servo so balls doon't fall out of the basket
		if(Joystick_Button(BUTTON_Y, CONTROLLER_2)) {
			Task_Kill(t_dropBall);
			Task_Spawn(t_resetDrop);
		}
		wait1Msec(1);
	}
}
