#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     irSensor,       sensorHiTechnicIRSeeker600)
#pragma config(Motor,  mtr_S1_C1_1,     leftWheel,     		tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     firstPickupMotor,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rightWheel,    		tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     liftMotor,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1, 		secondPickupMotor,	tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     liftMotor,     		tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,         	tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    dropServo,          tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    clampServoR,             tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    clampServoL,             tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    irServo,             tServoNone)
//#pragma config(Motor,  mtr_S1_C4_1,     liftMotor,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "includes.h"
#include "autoFunctions.h"

const int power = 100;
const int neg_power = -100;
const int lipPower = -100;
const int rampPower = -30;
const int rampLipTime = 1000;
const int rampTime = 1400;


task main() {
	Joystick_WaitForStart();

	motor[leftWheel] = lipPower;
	motor[rightWheel] = lipPower;
	wait1Msec(rampLipTime);
	motor[leftWheel] = rampPower;
	motor[rightWheel] = rampPower;
	wait1Msec(rampTime);


	servo[clampServoR] = endPosClampR;
	servo[clampServoL] = endPosClampL;
	//Task_Spawn(a_dropClamp);
}
